#!/bin/sh
# vim: tabstop=4 shiftwidth=4 expandtab
# 2024-12 by areq
#
# skrypt bedzie uruchamiany w chroot jako user build

set -e

[ $(id -un) = "root" ] && exit

cd /home/build/
PATH=/bin:/usr/bin

#Available options:
#addons: WEBIF WEBIF_LIVELOG WEBIF_JQUERY WITH_COMPRESS_WEBIF WITH_SSL HAVE_DVBAPI WITH_EXTENDED_CW WITH_NEUTRINO READ_SDT_CHARSETS CS_ANTICASC WITH_DEBUG MODULE_MONITOR WITH_LB CS_CACHEEX CS_CACHEEX_AIO CW_CYCLE_CHECK LCDSUPPORT LEDSUPPORT CLOCKFIX IPV6SUPPORT WITH_ARM_NEON WITH_SIGNING
#protocols: MODULE_CAMD33 MODULE_CAMD35 MODULE_CAMD35_TCP MODULE_NEWCAMD MODULE_CCCAM MODULE_CCCSHARE MODULE_GBOX MODULE_RADEGAST MODULE_SCAM MODULE_SERIAL MODULE_CONSTCW MODULE_PANDORA MODULE_GHTTP MODULE_STREAMRELAY
#readers: READER_NAGRA READER_NAGRA_MERLIN READER_IRDETO READER_CONAX READER_CRYPTOWORKS READER_SECA READER_VIACCESS READER_VIDEOGUARD READER_DRE READER_TONGFANG READER_BULCRYPT READER_GRIFFIN READER_DGCRYPT
#card_readers: CARDREADER_PHOENIX CARDREADER_INTERNAL CARDREADER_SC8IN1 CARDREADER_MP35 CARDREADER_SMARGO CARDREADER_DB2COM CARDREADER_STAPI CARDREADER_STAPI5 CARDREADER_STINGER CARDREADER_DRECAS

./config.sh --enable all --disable LCDSUPPORT LEDSUPPORT CLOCKFIX HAVE_DVBAPI  MODULE_CAMD33 MODULE_SCAM MODULE_SERIAL MODULE_GHTTP MODULE_PANDORA READER_DRE CARDREADER_DB2COM CARDREADER_STAPI CARDREADER_STAPI5 CARDREADER_DRECAS

make USE_LIBUSB=1 USE_PCSC=1 DEFAULT_PCSC_FLAGS="-I/usr/include/PCSC" CONF_DIR=/etc/oscam LIBDVBCSA_LIB="/usr/lib/libdvbcsa.a"

ls -t $CHROOT_DIR/home/build/Distribution/oscam* | head -n1 | while read f
do
    cp -a "$f" /home/build/output/
done

